// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialPulse.Infrastructure;

#nullable disable

namespace SocialPulse.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocialPulse.Core.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            QuestionId = 1,
                            Text = "Absolutely! We're thrilled about the upcoming updates. Get ready for enhanced user customization options, improved performance, and a brand-new feature that will take your experience to the next level. Stay tuned for the big reveal!"
                        },
                        new
                        {
                            Id = 2,
                            AdminId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            QuestionId = 2,
                            Text = "Great question! User privacy and data security are our top priorities. We implement robust encryption protocols, conduct regular security audits, and adhere to strict privacy policies. Rest assured, your data is in safe hands!"
                        },
                        new
                        {
                            Id = 3,
                            AdminId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            QuestionId = 3,
                            Text = "We're working on creating exciting community events and challenges. Imagine interactive quizzes, themed discussions, and collaborative projects. Your feedback matters, so if you have any event ideas, feel free to share! Let's make this platform even more vibrant together."
                        },
                        new
                        {
                            Id = 4,
                            AdminId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            QuestionId = 4,
                            Text = "We use a combination of automated tools and human moderation to ensure content aligns with our guidelines. We're committed to fostering an inclusive and respectful space for everyone. Your reports and feedback play a crucial role in keeping our community healthy!"
                        });
                });

            modelBuilder.Entity("SocialPulse.Core.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 3,
                            Text = "Pumped for my Sunday workout! Cardio or weights, what's your go-to fitness move?",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 3,
                            Text = "Yoga mornings are my favorite! Any yogis here? Share your favorite pose.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 6,
                            Text = "Heard about a local community garden initiative that's making a huge impact. Love seeing positive change in action!",
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 6,
                            Text = "My mood instantly lifts when I read about acts of kindness. Share a heartwarming news story that made your day!",
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 9,
                            Text = "Usually all about pop, but diving into classical this week. Any recommendations for a newbie?",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 9,
                            Text = "Jazz is my guilty pleasure! Drop your favorite jazz tune, and let's create a smooth playlist together.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 11,
                            Text = "Casablanca is an absolute classic! What's your favorite line from an old-school movie that still gives you chills?",
                            UserId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 11,
                            Text = "Bringing back the nostalgia with The Breakfast Club! Which classic film takes you on a trip down memory lane?",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("SocialPulse.Core.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("SocialPulse.Core.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Sports news and highlight from all major sports organizations",
                            IsDeleted = false,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "A place for major news from around the world",
                            IsDeleted = false,
                            Name = "News"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "The #1 community for music lovers",
                            IsDeleted = false,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "The goal of this group is to provide a place for discussion and news about films",
                            IsDeleted = false,
                            Name = "Movies"
                        });
                });

            modelBuilder.Entity("SocialPulse.Core.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MessageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("PostId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("SocialPulse.Core.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<bool>("Type")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique();

                    b.ToTable("Likes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 1,
                            Type = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 2,
                            Type = true,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 3,
                            Type = true,
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 4,
                            Type = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 5,
                            Type = true,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 6,
                            Type = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 7,
                            Type = true,
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 8,
                            Type = true,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 9,
                            Type = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 10,
                            Type = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 11,
                            Type = true,
                            UserId = 4
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 12,
                            Type = true,
                            UserId = 5
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 1,
                            Type = true,
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 2,
                            Type = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 3,
                            Type = true,
                            UserId = 4
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 4,
                            Type = true,
                            UserId = 4
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 5,
                            Type = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 6,
                            Type = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 7,
                            Type = true,
                            UserId = 5
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            PostId = 8,
                            Type = true,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("SocialPulse.Core.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 1, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Just finished a killer workout. What's up with you?",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 2, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "I'm just chilling and catching up on some reading. Any exciting plans for the weekend?",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 3, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Thinking of hitting the trails for a hike. Nature vibes, you know? What about you?",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 4, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "That sounds awesome! I might check out a new coffee shop downtown. Any book recommendations?",
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 5, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Absolutely! \"The Night Circus\" is a magical read. What kind of books are you into lately?",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 6, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "I'm on a sci-fi kick lately. Just finished \"Dune\" — epic world-building! Got any sci-fi gems in mind?",
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 6, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Nice choice! \"Neuromancer\" is a classic cyberpunk adventure. What's your favorite sci-fi element?",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 7, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Definitely the exploration of AI and its impact on society. Love those thought-provoking themes. What about you?",
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 8, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Same here! The ethical dilemmas in AI stories always get me thinking. Changing topics, any movie plans for the night?",
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 9, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Just downloaded a new indie film. \"Eternal Sunshine of the Spotless Mind.\" Heard it's a mind-bender. Have you seen it?",
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 10, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Absolutely love that one! Jim Carrey in a different light, you know?",
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 11, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Enjoy the journey! Let me know how you find it.",
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 12, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Thanks. Enjoy your hike and have a fantastic weekend!",
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            ConversationId = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 1, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Just got tickets to that new comedy show downtown. Interested in joining?",
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            ConversationId = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 2, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Sounds fun! Count me in. When's the show?",
                            UserId = 5
                        },
                        new
                        {
                            Id = 16,
                            ConversationId = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 3, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "It's this Saturday at 8 PM. Perfect way to kick off the weekend!",
                            UserId = 4
                        },
                        new
                        {
                            Id = 17,
                            ConversationId = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 4, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Awesome! Looking forward to it. Anything else happening this week?",
                            UserId = 5
                        },
                        new
                        {
                            Id = 18,
                            ConversationId = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 5, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Not much, just work and the usual. Any movie recommendations for a cozy night in?",
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            ConversationId = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 6, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "How about \"The Grand Budapest Hotel\"? Quirky and entertaining!",
                            UserId = 5
                        },
                        new
                        {
                            Id = 20,
                            ConversationId = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 7, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Great pick! I'll check it out. See you Saturday!",
                            UserId = 4
                        },
                        new
                        {
                            Id = 21,
                            ConversationId = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 8, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Can't wait! See you then!",
                            UserId = 5
                        },
                        new
                        {
                            Id = 22,
                            ConversationId = 3,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Hello?",
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            ConversationId = 3,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 1, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Hi.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 24,
                            ConversationId = 4,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Hello?",
                            UserId = 3
                        },
                        new
                        {
                            Id = 25,
                            ConversationId = 4,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 1, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Hi!",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("SocialPulse.Core.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TagId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TagId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            GroupId = 1,
                            IsDeleted = false,
                            Text = "Whether it's a slam dunk, a goal celebration, or a touchdown dance, the adrenaline rush of sports is unmatched! What's your favorite sport, and which team has your heart? Drop your cheers in the comments below!",
                            Title = "Game On!",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            GroupId = 1,
                            IsDeleted = false,
                            Text = "Sundays are made for epic sports battles! Which team are you cheering for today, and who's your MVP? Let the banter begin as we countdown to the final whistle. Game on, sports enthusiasts!",
                            Title = "Sunday Showdown!",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            GroupId = 1,
                            IsDeleted = false,
                            TagId = 3,
                            Text = "Whether it's hitting the gym, pounding the pavement, or mastering a new yoga pose, let's celebrate the fitness journey together! Share your favorite workout routine or fitness tips that keep you motivated. Let's inspire each other to break a sweat!",
                            Title = "Fitness Fanatics Unite!",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            GroupId = 2,
                            IsDeleted = false,
                            Text = "From global events to local buzz, staying updated is key! What news story caught your attention today? Share your thoughts and let's discuss the stories shaping our world. Knowledge is power!",
                            Title = "Headlines Unveiled: Stay Informed!",
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            GroupId = 2,
                            IsDeleted = false,
                            Text = "From groundbreaking discoveries to viral trends, what's been catching your eye in the news lately? Let's dive deep into the headlines and share our thoughts on the stories shaping our world. What's your take?",
                            Title = "Trending Topics Alert!",
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            GroupId = 2,
                            IsDeleted = false,
                            Text = "In a world full of headlines, let's focus on the positive stories that warm our hearts. Share a recent news piece that made you smile or inspired you. Together, let's spread positivity and celebrate the good vibes!",
                            Title = "Positive News Vibes Only!",
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            GroupId = 3,
                            IsDeleted = false,
                            Text = "Music is the soundtrack of our lives, and every beat tells a story. What song is playing on repeat for you right now? Share your current music obsession and let's create a playlist together! ",
                            Title = "Melody Magic",
                            UserId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            GroupId = 3,
                            IsDeleted = false,
                            TagId = 3,
                            Text = "Mondays are for reminiscing! Share a musical memory that takes you back in time. Whether it's a concert, a road trip playlist, or a special dance moment, let's rewind the clock and relive the magic together.",
                            Title = "Musical Memories Monday!",
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            GroupId = 3,
                            IsDeleted = false,
                            Text = "Let's shake things up! Challenge accepted: switch to a music genre you rarely explore. Share a song or artist from the new genre you're diving into, and let's see who discovers their next favorite tune!",
                            Title = "Genre Swap Challenge!",
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            GroupId = 4,
                            IsDeleted = false,
                            Text = "Whether it's a blockbuster hit or a hidden gem, what movie stole the show for you recently? Share your top picks, and let's swap recommendations for the ultimate movie night!",
                            Title = "Movie Buff Vibes",
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            GroupId = 4,
                            IsDeleted = false,
                            TagId = 3,
                            Text = "Dive into the archives with me! What classic movie holds a special place in your heart? Share your all-time favorite cinematic masterpiece, and let's reminisce about the golden era of film together.",
                            Title = "Cinematic Classics Countdown!",
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            GroupId = 4,
                            IsDeleted = false,
                            Text = "Planning a movie marathon this weekend? Share your must-watch movie list, and let's curate the ultimate movie night lineup! From comedies to dramas, let's make it an unforgettable cinematic experience.",
                            Title = "Movie Marathon Madness!",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("SocialPulse.Core.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "I'm curious about the future updates! Can you give us a sneak peek into any upcoming features or improvements?",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "How do you ensure the safety and privacy of user data on the platform?",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Are there any plans for community events or challenges on the platform? It would be awesome to engage with other users in a fun way!",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "How does content moderation work to ensure a positive and respectful environment?",
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "I'm curious about the technology behind the scenes. What kind of AI models power the platform, and how do you ensure they're unbiased?",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Are there plans to expand the app to support different languages and cultures?",
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "How can users contribute to the development of the platform? Any plans for a user feedback program?",
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "In case of technical issues or bugs, what's the best way for users to report them and get assistance?",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("SocialPulse.Core.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportedId")
                        .HasColumnType("int");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportedId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SocialPulse.Core.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("SocialPulse.Core.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Long"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Short"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Discussion"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Media"
                        });
                });

            modelBuilder.Entity("SocialPulse.Core.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "user@mail.com",
                            IsDeleted = false,
                            PasswordHash = "KnHtwSBaEBRQ4kirxu8qLLU+20BraHV95Aj4JJcTZyQ=",
                            PasswordSalt = "0dUI00v6BWmtxp8JCAyw9w==",
                            Role = 0,
                            Username = "TestUser"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "user2@mail.com",
                            IsDeleted = false,
                            PasswordHash = "KnHtwSBaEBRQ4kirxu8qLLU+20BraHV95Aj4JJcTZyQ=",
                            PasswordSalt = "0dUI00v6BWmtxp8JCAyw9w==",
                            Role = 1,
                            Username = "TestUser2"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "user3@mail.com",
                            IsDeleted = false,
                            PasswordHash = "KnHtwSBaEBRQ4kirxu8qLLU+20BraHV95Aj4JJcTZyQ=",
                            PasswordSalt = "0dUI00v6BWmtxp8JCAyw9w==",
                            Role = 1,
                            Username = "TestUser3"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "user4@mail.com",
                            IsDeleted = false,
                            PasswordHash = "KnHtwSBaEBRQ4kirxu8qLLU+20BraHV95Aj4JJcTZyQ=",
                            PasswordSalt = "0dUI00v6BWmtxp8JCAyw9w==",
                            Role = 1,
                            Username = "TestUser4"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "user5@mail.com",
                            IsDeleted = false,
                            PasswordHash = "KnHtwSBaEBRQ4kirxu8qLLU+20BraHV95Aj4JJcTZyQ=",
                            PasswordSalt = "0dUI00v6BWmtxp8JCAyw9w==",
                            Role = 1,
                            Username = "TestUser5"
                        });
                });

            modelBuilder.Entity("SocialPulse.Core.UserConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserConversations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            ConversationId = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            ConversationId = 2,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            ConversationId = 3,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            ConversationId = 3,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            ConversationId = 4,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            ConversationId = 4,
                            CreatedAt = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("SocialPulse.Core.Answer", b =>
                {
                    b.HasOne("SocialPulse.Core.User", "Admin")
                        .WithMany("Answers")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SocialPulse.Core.Question", "Question")
                        .WithOne("Answer")
                        .HasForeignKey("SocialPulse.Core.Answer", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SocialPulse.Core.Comment", b =>
                {
                    b.HasOne("SocialPulse.Core.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialPulse.Core.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialPulse.Core.Image", b =>
                {
                    b.HasOne("SocialPulse.Core.Message", "Message")
                        .WithMany("Images")
                        .HasForeignKey("MessageId");

                    b.HasOne("SocialPulse.Core.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId");

                    b.Navigation("Message");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialPulse.Core.Like", b =>
                {
                    b.HasOne("SocialPulse.Core.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialPulse.Core.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialPulse.Core.Message", b =>
                {
                    b.HasOne("SocialPulse.Core.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialPulse.Core.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialPulse.Core.Post", b =>
                {
                    b.HasOne("SocialPulse.Core.Group", "Group")
                        .WithMany("Posts")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialPulse.Core.Tag", "Tag")
                        .WithMany("Posts")
                        .HasForeignKey("TagId");

                    b.HasOne("SocialPulse.Core.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Tag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialPulse.Core.Question", b =>
                {
                    b.HasOne("SocialPulse.Core.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialPulse.Core.Report", b =>
                {
                    b.HasOne("SocialPulse.Core.User", "Reported")
                        .WithMany("Reports")
                        .HasForeignKey("ReportedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SocialPulse.Core.User", "Reporter")
                        .WithMany("MyReports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reported");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("SocialPulse.Core.Subscription", b =>
                {
                    b.HasOne("SocialPulse.Core.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("SocialPulse.Core.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialPulse.Core.UserConversation", b =>
                {
                    b.HasOne("SocialPulse.Core.Conversation", "Conversation")
                        .WithMany("Users")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialPulse.Core.User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialPulse.Core.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SocialPulse.Core.Group", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SocialPulse.Core.Message", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("SocialPulse.Core.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("SocialPulse.Core.Question", b =>
                {
                    b.Navigation("Answer");
                });

            modelBuilder.Entity("SocialPulse.Core.Tag", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SocialPulse.Core.User", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Comments");

                    b.Navigation("Conversations");

                    b.Navigation("Likes");

                    b.Navigation("Messages");

                    b.Navigation("MyReports");

                    b.Navigation("Posts");

                    b.Navigation("Questions");

                    b.Navigation("Reports");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
